### ISSUE TITLE
Running FactCheck

### ISSUE THREAD

**Issue by assadwatfa** [dice-group/FactCheck#23]
I've been trying to run factcheck on my local pc but i cant get it to work properly.

I've followed the steps as in the instructions of the core.

I indexed wikipedia using elasticsearch instead of using the bing api.

To run the defactodemo i imported the project into eclipse and ran the maven install then configured the run configuration to run the DefactoDemo. But i get the following error. NOTE: i want to use the local copy of wikipedia like stated in step 4 of the usage instructions

Could not execute query: org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://139.18.2.164:8080/solr/boa_en
org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://139.18.2.164:8080/solr/boa_en
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:583)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:942)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:957)
	at org.aksw.defacto.boa.BoaPatternSearcher.querySolrIndex(BoaPatternSearcher.java:126)
	at org.aksw.defacto.boa.BoaPatternSearcher.getNaturalLanguageRepresentations(BoaPatternSearcher.java:62)
	at org.aksw.defacto.search.query.QueryGenerator.generateSearchQueries(QueryGenerator.java:81)
	at org.aksw.defacto.search.query.QueryGenerator.getSearchEngineQueries(QueryGenerator.java:57)
	at org.aksw.defacto.Defacto.checkFact(Defacto.java:105)
	at org.aksw.defacto.Defacto.checkFacts(Defacto.java:200)
	at org.aksw.defacto.DefactoDemo.main(DefactoDemo.java:45)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:493)
	at java.base/sun.nio.ch.Net.connect(Net.java:482)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
	at java.base/java.net.Socket.connect(Socket.java:603)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:482)
	... 14 more

**Comment by MichaelRoeder** [comment]
Please excuse the late reply.

The program tries to access a service that was shut down recently. We clarify how you can setup the service locally. I will come back to you during the next days with more information.

We apologize for any inconveniences this may cause.

**Comment by TortugaAttack** [comment]
OK. I figured it out. 
The following does the job to start a solr server using the boa lucene indexes. (you need to use solr 3.6.2 and java 8 or lower (5-8 should work)
```bash
#just a working directory
mkdir solr_factcheck && cd solr_factcheck
#getting solr 3.6.2 (all other versions won't work)
wget https://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.tgz 
tar -xzvf apache-solr-3.6.2.tgz  && cd apache-solr-3.6.2/example
#changing the name to boa_en 
sed -i -e 's/collection1/boa_en/g' solr/solr.xml 
#changing the port to 8080
sed -i -e 's/8983/8080/g' solr/conf/solrconfig.xml
sed -i -e 's/8983/8080/g' etc/jetty.xml
#Creating the directories for the index 
mkdir solr/data/
mkdir solr/data/index/
#Getting the lucene index 
wget https://github.com/dice-group/boa-data/raw/master/boa_en_10.tar.gz 
tar -xzvf boa_en_10.tar.gz -C solr/data/index/
rm  boa_en_10.tar.gz 
#Use Java 8 or lower, everything higher than 8 won't work. 
#Starting the jetty server on port 8080 in the back 
/usr/lib/jvm/java-8-openjdk/bin/java -jar start.jar & 
```

afterwards http://127.0.0.1:8080/solr/boa_en/ should be online and query-a ble with the boa_en_10 dataset from https://github.com/dice-group/boa-data

**Comment by TortugaAttack** [comment]
Additionally if you want to use all three language indexes use the following 

```bash
#just a working directory
mkdir solr_factcheck && cd solr_factcheck
#getting solr 3.6.2 (all other versions won't work)
wget https://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.tgz 
tar -xzvf apache-solr-3.6.2.tgz  && cd apache-solr-3.6.2/example
#changing the name to boa_en 
sed -i -e 's/collection1/boa_en/g' solr/solr.xml 
#changing the port to 8080
sed -i -e 's/8983/8080/g' solr/conf/solrconfig.xml
sed -i -e 's/8983/8080/g' etc/jetty.xml
#Creating the directories for the index 
mkdir solr/boa_en/
mkdir solr/boa_en/data/
mkdir solr/boa_en/data/index/
cp -r solr/conf/ solr/boa_en/conf/
mkdir solr/boa_de/
mkdir solr/boa_de/data/
mkdir solr/boa_de/data/index/
cp -r solr/conf/ solr/boa_de/conf/
mkdir solr/boa_fr/
mkdir solr/boa_fr/data/
mkdir solr/boa_fr/data/index/
cp -r solr/conf/ solr/boa_fr/conf/
#Getting the lucene index 
wget https://github.com/dice-group/boa-data/raw/master/boa_en_10.tar.gz 
wget https://github.com/dice-group/boa-data/raw/master/boa_de_10.tar.gz 
wget https://github.com/dice-group/boa-data/raw/master/boa_fr_10.tar.gz 
tar -xzvf boa_en_10.tar.gz -C solr/boa_en/data/index/
rm  boa_en_10.tar.gz 
tar -xzvf boa_de_10.tar.gz -C solr/boa_de/data/index/
rm  boa_de_10.tar.gz 
tar -xzvf boa_fr_10.tar.gz -C solr/boa_fr/data/index/
rm  boa_fr_10.tar.gz 
```

Now before you start the service exchange `<cores ...> ...</cores>` to following in the `solr/solr.xml`

```xml
<cores adminPath="/admin/cores" defaultCoreName="boa_en">
    <core name="boa_en" instanceDir="boa_en" />
    <core name="boa_de" instanceDir="boa_de" />
    <core name="boa_fr" instanceDir="boa_fr" />
  </cores>
```

then start jetty 
```bash
#Use Java 8 or lower, everything higher than 8 won't work. 
#Starting the jetty server on port 8080 in the back 
/usr/lib/jvm/java-8-openjdk/bin/java -jar start.jar & 
```

**Comment by TortugaAttack** [comment]
Afterwards you need to change the URLs in the defacto.ini [factcheck-core/src/main/resources/defacto.ini](https://github.com/dice-group/FactCheck/blob/256609351dc87c6261ce11780a042ab9510ab8ee/factcheck-core/src/main/resources/defacto.ini#L42)

Not sure if FactCheck is using port 8080. If so please adjust the `sed ` calls in accordingly

**Comment by MichaelRoeder** [comment]
@assadwatfa did this fix your issues?
